### ISSUE TITLE
Add build instructions to readme

### ISSUE THREAD

**Issue by Thunderforge** [SteveNew/POXStudio#1]
Right now, the readme does not include instructions on how to build the project. It would be very helpful to include them so that others can build it.

**Comment by Aldarith** [comment]
Ditto on this, really want to get into SOA but can't!

**Comment by SteveNew** [comment]
Sorry - missed this - README updated. I had not guessed that build instructions were needed for an application this simple - my bad.

**Comment by Thunderforge** [comment]
It may be simple to those who are familiar with Delphi; others who are less familiar with Delphi but are interested in Siege of Avalon (like me) may not know the steps.

Thanks for adding them!

**Comment by SteveNew** [comment]
You are right - I should not take it for granted - I do myself also struggle when I get into some new environments that I feel work backwards.

BTW: I have put up a Win64 binary under releases.
